pages:
  image: mmoy/riscv-latex-python:2024 # Has LaTeX + riscv + python + ANTLR. See docker/Dockerfile in this repo.
  variables:
    ANTLR4: 'java -jar /opt/antlr-4.13.1-complete.jar'
  rules:
    - changes:
      - .gitlab-*
      - MiniC/*
      - MiniC/**/*
  script:
    - ./.gitlab-pages.sh
  artifacts:
    paths:
    - public/
